/** ISO-2 / ISO-3 country code -> display name (mirrors vehere-ui country_data_isocode.json). */
const COUNTRY_NAMES: Record<string, string> = {
  ABW: "Aruba",
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AFG: "Afghanistan",
  AG: "Antigua and Barbuda",
  AGO: "Angola",
  AI: "Anguilla",
  AIA: "Anguilla",
  AL: "Albania",
  ALB: "Albania",
  AM: "Armenia",
  AND: "Andorra",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  ARE: "United Arab Emirates",
  ARG: "Argentina",
  ARM: "Armenia",
  AS: "American Samoa",
  ASM: "American Samoa",
  AT: "Austria",
  ATA: "Antarctica",
  ATF: "French Southern Territories",
  ATG: "Antigua and Barbuda",
  AU: "Australia",
  AUS: "Australia",
  AUT: "Austria",
  AW: "Aruba",
  AZ: "Azerbaijan",
  AZE: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BDI: "Burundi",
  BE: "Belgium",
  BEL: "Belgium",
  BEN: "Benin",
  BES: "Bonaire, Sint Eustatius and Saba",
  BF: "Burkina Faso",
  BFA: "Burkina Faso",
  BG: "Bulgaria",
  BGD: "Bangladesh",
  BGR: "Bulgaria",
  BH: "Bahrain",
  BHR: "Bahrain",
  BHS: "Bahamas",
  BI: "Burundi",
  BIH: "Bosnia and Herzegovina",
  BJ: "Benin",
  BL: "Saint Barthelemy",
  BLM: "Saint Barthelemy",
  BLR: "Belarus",
  BLZ: "Belize",
  BM: "Bermuda",
  BMU: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BOL: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BRA: "Brazil",
  BRB: "Barbados",
  BRN: "Brunei",
  BS: "Bahamas",
  BT: "Bhutan",
  BTN: "Bhutan",
  BV: "Bouvet Island",
  BVT: "Bouvet Island",
  BW: "Botswana",
  BWA: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CAF: "Central African Republic",
  CAN: "Canada",
  CC: "Cocos",
  CCK: "Cocos",
  CD: "Congo (the Democratic Republic of the)",
  CF: "Central African Republic",
  CG: "Congo",
  CH: "Switzerland",
  CHE: "Switzerland",
  CHL: "Chile",
  CHN: "China",
  CI: "Ivory Coast",
  CIV: "Ivory Coast",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CMR: "Cameroon",
  CN: "China",
  CO: "Colombia",
  COD: "Congo (the Democratic Republic of the)",
  COG: "Congo",
  COK: "Cook Islands",
  COL: "Colombia",
  COM: "Comoros",
  CPV: "Cabo Verde",
  CR: "Costa Rica",
  CRI: "Costa Rica",
  CU: "Cuba",
  CUB: "Cuba",
  CUW: "Curacao",
  CV: "Cabo Verde",
  CW: "Curacao",
  CX: "Christmas Island",
  CXR: "Christmas Island",
  CY: "Cyprus",
  CYM: "Cayman Islands",
  CYP: "Cyprus",
  CZ: "Czechia",
  CZE: "Czechia",
  DE: "Germany",
  DEU: "Germany",
  DJ: "Djibouti",
  DJI: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DMA: "Dominica",
  DNK: "Denmark",
  DO: "Dominican Republic",
  DOM: "Dominican Republic",
  DZ: "Algeria",
  DZA: "Algeria",
  EC: "Ecuador",
  ECU: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EGY: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ERI: "Eritrea",
  ES: "Spain",
  ESH: "Western Sahara",
  ESP: "Spain",
  EST: "Estonia",
  ET: "Ethiopia",
  ETH: "Ethiopia",
  FI: "Finland",
  FIN: "Finland",
  FJ: "Fiji",
  FJI: "Fiji",
  FK: "Falkland Islands (Islas Malvinas)",
  FLK: "Falkland Islands (Islas Malvinas)",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  FRA: "France",
  FRO: "Faroe Islands",
  FSM: "Micronesia",
  GA: "Gabon",
  GAB: "Gabon",
  GB: "United Kingdom",
  GBR: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GEO: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GGY: "Guernsey",
  GH: "Ghana",
  GHA: "Ghana",
  GI: "Gibraltar",
  GIB: "Gibraltar",
  GIN: "Guinea",
  GL: "Greenland",
  GLP: "Guadeloupe",
  GM: "Gambia",
  GMB: "Gambia",
  GN: "Guinea",
  GNB: "Guinea-Bissau",
  GNQ: "Equatorial Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GRC: "Greece",
  GRD: "Grenada",
  GRL: "Greenland",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GTM: "Guatemala",
  GU: "Guam",
  GUF: "French Guiana",
  GUM: "Guam",
  GUY: "Guyana",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HKG: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HMD: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HND: "Honduras",
  HR: "Croatia",
  HRV: "Croatia",
  HT: "Haiti",
  HTI: "Haiti",
  HU: "Hungary",
  HUN: "Hungary",
  ID: "Indonesia",
  IDN: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IMN: "Isle of Man",
  IN: "India",
  IND: "India",
  IO: "British Indian Ocean Territory",
  IOT: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IRL: "Ireland",
  IRN: "Iran",
  IRQ: "Iraq",
  IS: "Iceland",
  ISL: "Iceland",
  ISR: "Israel",
  IT: "Italy",
  ITA: "Italy",
  JAM: "Jamaica",
  JE: "Jersey",
  JEY: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JOR: "Jordan",
  JP: "Japan",
  JPN: "Japan",
  KAZ: "Kazakhstan",
  KE: "Kenya",
  KEN: "Kenya",
  KG: "Kyrgyzstan",
  KGZ: "Kyrgyzstan",
  KH: "Cambodia",
  KHM: "Cambodia",
  KI: "Kiribati",
  KIR: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KNA: "Saint Kitts and Nevis",
  KOR: "South Korea",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KWT: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LAO: "Laos",
  LB: "Lebanon",
  LBN: "Lebanon",
  LBR: "Liberia",
  LBY: "Libya",
  LC: "Saint Lucia",
  LCA: "Saint Lucia",
  LI: "Liechtenstein",
  LIE: "Liechtenstein",
  LK: "Sri Lanka",
  LKA: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LSO: "Lesotho",
  LT: "Lithuania",
  LTU: "Lithuania",
  LU: "Luxembourg",
  LUX: "Luxembourg",
  LV: "Latvia",
  LVA: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MAC: "Macao",
  MAF: "Saint Martin (French part)",
  MAR: "Morocco",
  MC: "Monaco",
  MCO: "Monaco",
  MD: "Moldova",
  MDA: "Moldova",
  MDG: "Madagascar",
  MDV: "Maldives",
  ME: "Montenegro",
  MEX: "Mexico",
  MF: "Saint Martin (French part)",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MHL: "Marshall Islands",
  MK: "Republic of North Macedonia",
  MKD: "Republic of North Macedonia",
  ML: "Mali",
  MLI: "Mali",
  MLT: "Malta",
  MM: "Myanmar",
  MMR: "Myanmar",
  MN: "Mongolia",
  MNE: "Montenegro",
  MNG: "Mongolia",
  MNP: "Northern Mariana Islands",
  MO: "Macao",
  MOZ: "Mozambique",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MRT: "Mauritania",
  MS: "Montserrat",
  MSR: "Montserrat",
  MT: "Malta",
  MTQ: "Martinique",
  MU: "Mauritius",
  MUS: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MWI: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MYS: "Malaysia",
  MYT: "Mayotte",
  MZ: "Mozambique",
  NA: "Namibia",
  NAM: "Namibia",
  NC: "New Caledonia",
  NCL: "New Caledonia",
  NE: "Niger",
  NER: "Niger",
  NF: "Norfolk Island",
  NFK: "Norfolk Island",
  NG: "Nigeria",
  NGA: "Nigeria",
  NI: "Nicaragua",
  NIC: "Nicaragua",
  NIU: "Niue",
  NL: "Netherlands",
  NLD: "Netherlands",
  NO: "Norway",
  NOR: "Norway",
  NP: "Nepal",
  NPL: "Nepal",
  NR: "Nauru",
  NRU: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  NZL: "New Zealand",
  OM: "Oman",
  OMN: "Oman",
  PA: "Panama",
  PAK: "Pakistan",
  PAN: "Panama",
  PCN: "Pitcairn",
  PE: "Peru",
  PER: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PHL: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PLW: "Palau",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn",
  PNG: "Papua New Guinea",
  POL: "Poland",
  PR: "Puerto Rico",
  PRI: "Puerto Rico",
  PRK: "North Korea",
  PRT: "Portugal",
  PRY: "Paraguay",
  PS: "Palestine, State of",
  PSE: "Palestine, State of",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  PYF: "French Polynesia",
  QA: "Qatar",
  QAT: "Qatar",
  RE: "Reunion",
  REU: "Reunion",
  RO: "Romania",
  ROU: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RUS: "Russia",
  RW: "Rwanda",
  RWA: "Rwanda",
  SA: "Saudi Arabia",
  SAU: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SDN: "Sudan",
  SE: "Sweden",
  SEN: "Senegal",
  SG: "Singapore",
  SGP: "Singapore",
  SGS: "South Georgia and the South Sandwich Islands",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SHN: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SJM: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SLB: "Solomon Islands",
  SLE: "Sierra Leone",
  SLV: "El Salvador",
  SM: "San Marino",
  SMR: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SOM: "Somalia",
  SPM: "Saint Pierre and Miquelon",
  SR: "Suriname",
  SRB: "Serbia",
  SS: "South Sudan",
  SSD: "South Sudan",
  ST: "Sao Tome and Principe",
  STP: "Sao Tome and Principe",
  SUR: "Suriname",
  SV: "El Salvador",
  SVK: "Slovakia",
  SVN: "Slovenia",
  SWE: "Sweden",
  SWZ: "Estonia",
  SX: "Sint Maarten (Dutch part)",
  SXM: "Sint Maarten (Dutch part)",
  SY: "Syrian Arab Republic",
  SYC: "Seychelles",
  SYR: "Syrian Arab Republic",
  SZ: "Estonia",
  TC: "Turks and Caicos Islands",
  TCA: "Turks and Caicos Islands",
  TCD: "Chad",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TGO: "Togo",
  TH: "Thailand",
  THA: "Thailand",
  TJ: "Tajikistan",
  TJK: "Tajikistan",
  TK: "Tokelau",
  TKL: "Tokelau",
  TKM: "Turkmenistan",
  TL: "Timor-Leste",
  TLS: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TON: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TTO: "Trinidad and Tobago",
  TUN: "Tunisia",
  TUR: "Turkey",
  TUV: "Tuvalu",
  TV: "Tuvalu",
  TW: "Taiwan (Province of China)",
  TWN: "Taiwan (Province of China)",
  TZ: "Tanzania, United Republic of",
  TZA: "Tanzania, United Republic of",
  UA: "Ukraine",
  UG: "Uganda",
  UGA: "Uganda",
  UKR: "Ukraine",
  UM: "United States Minor Outlying Islands",
  UMI: "United States Minor Outlying Islands",
  URY: "Uruguay",
  US: "United States",
  USA: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  UZB: "Uzbekistan",
  VA: "Holy See",
  VAT: "Holy See",
  VC: "Saint Vincent and the Grenadines",
  VCT: "Saint Vincent and the Grenadines",
  VE: "Venezuela (Bolivarian Republic of)",
  VEN: "Venezuela (Bolivarian Republic of)",
  VG: "Virgin Islands (British)",
  VGB: "Virgin Islands (British)",
  VI: "Virgin Islands (U.S.)",
  VIR: "Virgin Islands (U.S.)",
  VN: "VietNam",
  VNM: "VietNam",
  VU: "Vanuatu",
  VUT: "Vanuatu",
  WF: "Wallis and Futuna",
  WLF: "Wallis and Futuna",
  WS: "Samoa",
  WSM: "Samoa",
  YE: "Yemen",
  YEM: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZAF: "South Africa",
  ZM: "Zambia",
  ZMB: "Zambia",
  ZW: "Zimbabwe",
  ZWE: "Zimbabwe",
};

/** SOI docs store `countries_a2_codes`; render the readable name when we know it. */
export function countryName(code: string): string {
  if (!code) return "Unknown";
  return COUNTRY_NAMES[String(code).toUpperCase()] || code;
}
